version: '3'

tasks:
  installdeps:
    desc: Instala las dependencias del proyecto
    cmds:
      - go get -d -v ./...

  build:
    desc: Comprueba que los paquetes compilan bien y no tienen errores
    cmds:
      - go build -v ./...

  test:
    desc: Ejecuta todos los tests definidos para el proyecto
    cmds:
      - go test -v ./...

  dockertest:
    desc: Ejecuta el contenedor docker, que pasa los tests del proyecto
    cmds:
      - docker run -t -v $(pwd):/app/test -it ostfind