version: '3'

tasks:
  install:
    desc: Instala los ficheros en el GOPATH de la máquina
    cmds:
      - echo "Aún no se tiene un main"

  build:
    desc: Comprueba que los paquetes compilan bien y no tienen errores
    cmds:
      - go build -v ./...

  test:
    desc: Ejecuta todos los tests definidos para el proyecto
    cmds:
      - go test -v ./...

  installdeps:
    desc: Instala las dependencias del proyecto
    cmds:
      - go mod download

  dockertest:
    desc: Ejecuta el contenedor docker, que pasa los tests del proyecto
    cmds:
      - docker run -t -v $(pwd):/app/test jlgallego99/ostfind