version: '3'

tasks:
  check:
    desc: Comprueba que los paquetes compilan bien y no tienen errores
    cmds:
      - go build -v ./internal/cancion
      - go build -v ./internal/obra

  test:
    desc: Ejecuta todos los tests definidos para el proyecto
    cmds:
      - go test -v ./...