name: GHCR jlgallego99/ostfind

# El evento que activa este workflow en este caso es el de "push"
# Cada vez que se actualice la rama principal (main) del repositorio, se construirá y subirá el contenedor
on:
  push:
    branches:
      - 'main'

# Todas las acciones que va a ejecutar este workflow se listan aquí
jobs:
  docker:
    # Especificar el ambiente donde ejecutar el workflow, en este caso linux es lo más adecuado y rápido
    runs-on: ubuntu-latest
    steps:
      # Comprobar el estado del repositorio para que el propio workflow pueda acceder a él
      - name: Checkout
        uses: actions/checkout@v2

      # Hacer login en GHCR
      - name: Login to Github Container Registry
        uses: docker/login-action@v1.10.0 # Última versión tageada de la acción
        with:
          # El registro donde se va a hacer login para luego subir el contenedor (ghcr)
          registry: ghcr.io
          username: ${{ github.actor }} # Variable de entorno que simplemente extrae el nombre de usuario del que lo llama (jlgallego99)
          password: ${{ secrets.GITHUB_TOKEN }} # Acceder de forma normal a la contraseña en los secretos del repo (esta la genera las github actions automaticamente)

      # Construye el contenedor y lo sube a GHCR
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          # Indica que se sube la imagen al registro si ha compilado
          push: true
          # user será jlgallego99, la app será ostfind y latest es el tag (última versión)
          tags: jlgallego99/ostfind:latest